version: 0.2

phases:
  install:
    runtime-versions:
      java: 8
  pre_build:
    commands:
      - echo Not sure what to do yet
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
